### PR TITLE
Feed: gluster quota's accounting.

### PR DESCRIPTION
**Pull request by harigowtham**
It is split into 3 part, this is the first part.

Signed-off-by: hari gowtham <hgowtham@redhat.com>

### CODE REVIEW

**Comment by harigowtham** [comment]
@amarts please do take a look when you have time.

**Review by amarts — APPROVED** [review]
This is fine. But if you had added a tag 'glusterfs' or 'gluster' this would have appeared in planet.gluster.org without any changes.

**Comment by harigowtham** [comment]
Can you explain what you mean by tag here? If its the tags that medium asks us to use, I have tagged it for under glusterfs, filesystems, quota, and so on.

**Comment by amarts** [comment]
https://github.com/gluster/planet-gluster/blob/master/data/feeds.yml#L260 already contains the feed details. So, it should have been there. Can you check why its already not in planet.gluster.org ? Should we be pulling some data? I am OK to merge this, but adding 1 blog at a time is not a good solution IMO.

**Comment by amarts** [comment]
and notice that your blog is already in the feed, just not yet published. https://medium.com/feed/tag/glusterfs

**Comment by harigowtham** [comment]
I'm not aware of how this works. There isn't any information to mention on the fact that the blogs with gluster / glusterfs tags are taken in automatically, until you said it now. The same goes for publishing the blogs. 
My understanding is, we send PRs for blogs that we want to be a part of the planet gluster. Once there are a good number of PR, the publishing work is done by the maintainer or does it automatically publish? 
If we have a post with it tagged to gluster / glusterfs, we add them automatically to the feed. These need not be explicitly sent as a PR.
Also I see a lot of blogs in the feed while the planet gluster site doesn't have them.
So it would be great if you could let me know what should be done from my end.

**Comment by amarts** [comment]
I too don't know the details of how this repo works, and where are documents for the same. . Will see what we can do about it.

**Pull request merged**
